export const subtripConfig = [
  { id: 'routeCd', label: 'Route Code', type: 'text' },
  { id: 'customerId', label: 'Customer ID', type: 'text' },
  { id: 'loadingPoint', label: 'Loading Point', type: 'text' },
  { id: 'unloadingPoint', label: 'Unloading Point', type: 'text' },
  // { id: 'loadingWeight', label: 'Loading Weight', type: 'number' },
  // { id: 'unloadingWeight', label: 'Unloading Weight', type: 'number' },
  { id: 'startDate', label: 'Start Date', type: 'date' },
  // { id: 'endDate', label: 'End Date', type: 'date' },
  // { id: 'startKm', label: 'Start Km', type: 'number' },
  // { id: 'endKm', label: 'End Km', type: 'number' },
  { id: 'rate', label: 'Rate', type: 'number' },
  { id: 'subtripStatus', label: 'Status', type: 'text' },
  // { id: 'invoiceNo', label: 'Invoice No', type: 'text' },
  // { id: 'shipmentNo', label: 'Shipment No', type: 'text' },
  // { id: 'orderNo', label: 'Order No', type: 'text' },
  // { id: 'ewayBill', label: 'E-Way Bill', type: 'text' },
  // { id: 'ewayExpiryDate', label: 'E-Way Expiry Date', type: 'date' },
  { id: 'materialType', label: 'Material Type', type: 'text' },
  { id: 'quantity', label: 'Quantity', type: 'number' },
  // { id: 'grade', label: 'Grade', type: 'text' },
  // { id: 'dieselLtr', label: 'Diesel Litres', type: 'number' },
  // { id: 'detentionTime', label: 'Detention Time', type: 'number' },
  // { id: 'tds', label: 'TDS', type: 'number' },
  // { id: 'deductedWeight', label: 'Deducted Weight', type: 'number' },
];
